// Generated by NSTOK AI Software Factory
export interface AppConfigType {
  name: string;
  reusedFeatures: string[];
  newFeatures: string[];
  uiComponents: string[];
  dbEntities: string[];
}

export const AppConfig: AppConfigType = {
  name: 'nstok-laundry-app',
  reusedFeatures: ['@nstok/nstok-feature-customer'],
  newFeatures: ['@nstok/nstok-feature-laundry-tracking'],
  uiComponents: ['Button', 'SearchInput', 'Card', 'DataTable'],
  dbEntities: ['service_tickets', 'service_ticket_items', 'service_status_logs']
};
