// Generated by NSTOK AI Software Factory
import { ApplicationComposition } from '@nstok/core';

export const AppConfig = {
  name: 'nstok-laundry-app',
  reusedFeatures: [],
  newFeatures: [
  "customer"
],
  uiComponents: [
  "Button",
  "SearchInput"
],
  dbEntities: []
};
